kind: pipeline
name: default

steps:
  - name: kalibrate-build
    image: voltagex/fedora-mingw64-rtlsdr
    commands:
      - pushd /drone/src/ && bash drone-build.sh

  - name: publish  
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: rtl.tar.gz
      when:
        event: tag